/*
 * This class is a panel where the detection result will be drawn
 */


import java.awt.Color;
import java.awt.image.BufferedImage;



/**
 *
 * @author Bullseye
 */
import java.awt.image.BufferedImage;

public class DrawablePanel extends javax.swing.JPanel {
    BufferedImage image;
    aiva.SafetyCheckDetection scDetection;

    /**
     * Creates new form DrawablePanel
     */
    public DrawablePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(java.awt.Graphics g){
        super.paintComponent(g);
        if(image != null){
            g.drawImage(image, 0, 0, this);
        }
        if(scDetection != null) {
            java.util.ArrayList<aiva.BoundingBox> bbList = scDetection.getBbList();
            for(int i=0; i<bbList.size();i++){
                aiva.BoundingBox bb = bbList.get(i);
                g.setColor(Color.RED);
                g.drawRect(bb.getX1(), bb.getY1(), bb.getX2()-bb.getX1(), bb.getY2()-bb.getY1());
                
            }
        }
    }

    public BufferedImage getImage() {
        return image;
    }

    public void setImage(BufferedImage image) {
        this.image = image;
    }

    public aiva.SafetyCheckDetection getScDetection() {
        return scDetection;
    }

    public void setScDetection(aiva.SafetyCheckDetection scDetection) {
        this.scDetection = scDetection;
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
